config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'high_voltage/pages#show', id: 'about'

  namespace :admin do
    resources :members
    resources :courses
    resources :documents
    resources :certificates do 
      member do 
        get :download
      end
    end
  end

  authenticated :user do
    root 'admin/courses#index', as: :authenticated_root
  end

  resources :documents

end

app/models/address.rb
class Address < ApplicationRecord

  validates :first_name,
            :last_name,
            presence: true

  validates :mobile_number,
            numericality: true,
            allow_blank: true

  validates :email_id,
          uniqueness: true,
          format: { with: RubyRegex::Email }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certificate_general.rb
class CertificateGeneral < ApplicationRecord

  self.table_name = 'view_certificate_general'
  self.primary_key = 'id'

end

app/models/course.rb
class Course < ApplicationRecord

  validates :name, 
            :interval,
            presence: true

  validates :name,
            uniqueness: true

  has_many :course_members
  has_many :members, through: :course_members

  accepts_nested_attributes_for :members

end

app/models/course_member.rb
class CourseMember < ApplicationRecord
  belongs_to :member
  belongs_to :course
end

app/models/document.rb
class Document < ApplicationRecord

  has_attached_file :document_list,
           styles: { medium: "300x300>", thumb: "100x100>"},
           s3_protocol: 'https'

  validates :document_list,
             presence: true

  validates_attachment_content_type :document_list, :content_type => ['image/jpeg', 'image/png']
  validates :document_list, attachment_presence: true

end

app/models/member.rb
class Member < ApplicationRecord

  has_one :address, as: :resource, dependent: :destroy
  has_many :course_members
  has_many :courses, through: :course_members

  delegate :first_name, to: :address, allow_nil: true
  delegate :middle_name, to: :address, allow_nil: true
  delegate :last_name, to: :address, allow_nil: true
  delegate :email_id, to: :address, allow_nil: true
  delegate  :interval, to: :courses
  delegate  :mobile_number, to: :address, allow_nil: true

  accepts_nested_attributes_for :address

  attr_reader :course

  scope :certificate_not_generated, -> { where( certificategenerated: false ) }

  def name
    full_name = ''
    full_name << first_name.to_s << middle_name.to_s << last_name.to_s
    full_name
  end

  def generate_certificate!
    if course_completed?
      self.update_attribute(:certificategenerated, true)
    end
  end

  def course_completed?
    (((Time.now - self.created_at)/1.day).round).to_i >=  self.course_duration*30
  end 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < AdminController

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      respond_to do |format|
        format.js
      end
    else
      render 'new'
    end
  end

  private

  def course_params
    params.require(:course).permit(
      :name,
      :interval
    )
  end

end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < AdminController

  include GallaryController

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to admin_documents_path
    else
      render 'new'
    end
  end

  private

  def document_params
    params.require(:document).permit(
      :document_list
    )
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < AdminController

  before_action :find_course

  def index
    @members = @course.try(:members)
  end

  def new
    @member = @course.members.build
    @member.course_duration = @course.interval
    @address = @member.build_address
  end

  def create
    @member = @course.members.new(member_params)
    if @course.save && @member.save
      respond_to do |format|
        flash[:notice] = 'Member is created successfully'
        format.js
      end
    else
      render 'new'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    if @member.destroy
        flash[:notice] = 'Member is destroyed successfully'
        redirect_to admin_members_path(course: params[:course])
    else
      render 'new'
    end
  end


  private

  def find_course
    @course = Course.find_by_name(params[:course])
  end

  def member_params
    params.require(:member).permit(
      :fees,
      :course_duration,
      address_attributes:
      [
        :first_name,
        :middle_name,
        :last_name,
        :email_id,
        :mobile_number
      ]
    )
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_filter :valid_request

  protected

  def after_sign_in_path_for(resource)
    admin_courses_path
  end

  def valid_request
    if restricted_action
      redirect_to new_user_session_path
    end
  end

  def restricted_action
    controller_name == 'registrations' && action_name == 'new'
  end

end

app/controllers/concerns/gallary_controller.rb
module GallaryController
  extend ActiveSupport::Concern
  included do
    def index
      @documents = Document.all
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include GallaryController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def members_tabs(course)
    Course.all.map(&:name).each do |course_name|
      course.item course_name, course_name, admin_members_path(course: course_name),
        highlights_on: lambda { params[:course] == course_name }
    end
  end

  def custom_navigation
    'navbar-navbar-default.custom-nav' 
  end

  def is_pdf_request?
    params[:format] == 'pdf'
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/layouts/_navigation.html.slim
ul.nav.navbar-nav
  li.list
    = link_to 'About Us', page_path('about'), id: 'a-custom'
  li.list
    = link_to 'Gallary', documents_path, id: 'a-custom'
  li.list
    = link_to 'Offering Courses', page_path('offering_course'), id: 'a-custom'
  li.list
    = link_to 'Carrier', page_path('carrier'), id: 'a-custom'
  li.list
   = link_to 'Contact Us', page_path('contact_us'), id: 'a-custom'

app/views/layouts/_user_navigation.html.slim
= render_navigation level: 1..2, expand_all: true, renderer: :bootstrap

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Ims
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    - if user_signed_in?
      = javascript_include_tag 'navigation/navigation'
  body
    header
      .container-fluid.custom-head
        .col-sm-2
          = image_tag('computer_logo.png', size: "80x80",  class: "center")
        .col-sm-5
          = image_tag('name_logo.gif', size: '100*100' )
        .col-sm-5
          .pull-right
            - if user_signed_in?
              = link_to image_tag('logout_logo.png'), destroy_user_session_path, method: :delete,
                data: { confirm: 'Are you sure you want to logout?' }, class: 'icon btn'
            - else
              = link_to image_tag('admin_login.png'), new_user_session_path, class: 'icon btn'
      nav.navbar-navbar-default.custom-nav 
        .container-fluid
          .navbar-header
            button.navbar-toggle data-toggle="collapse" data-target="#myNavbar" type = 'button'
              span.icon-bar
              span.icon-bar
              span.icon-bar
          #myNavbar.collapse.navbar-collapse
            - if user_signed_in?
              = render 'layouts/user_navigation'
            - else
              = render 'layouts/navigation'
      - if user_signed_in?
        .page-content
          = render_navigation level: 3, expand_all: true
      .container
        - if notice
          p.alert.alert-success
            = notice
        - if alert
          p.alert.alert-danger
            = alert
      #content
        = yield
    - if user_signed_in?
      .footer.space-20
        .container.no-padding
          .col-md-6.no-padding.col-xs-7.col-sm-8
            small.copyright Copyright © RBA Computers #{Time.now.year}, All Rights Reserved
          .pull-right
            span RBA
    - else
      br
      footer
        .container
          .col-sm-4
            .row
              h4 = 'Address:'
              p style= "color:#ccc;"
                | Dilip Electronic Main Road Lachragardh
            .row
          .col-sm-1
          .col-sm-3
            .row
              h4 = 'Contact:'
              p style= "color:#ccc;"
                | +91 - 7544802173 
                br
                | +91 - 9430742215
            .row
          .col-sm-1
          .col-sm-3
            .row
              h4 = 'Email:'
              p style= "color:#ccc;"
                | rbacomputercenter@gmail.com
            .row

app/views/pages/about.html.slim
#myCarousel.carousel.slide data-ride="carousel" 
  /! Indicators
  ol.carousel-indicators
    li.active data-slide-to="0" data-target="#myCarousel" 
    li data-slide-to="1" data-target="#myCarousel"
    li data-slide-to="2" data-target="#myCarousel"
    li data-slide-to="3" data-target="#myCarousel"
    li data-slide-to="4" data-target="#myCarousel"
  /! Wrapper for slides
  .carousel-inner
    .item.active
      = image_tag 'image4.jpg', alt: 'image4', class: 'tales'
    .item
      = image_tag 'image5.jpg', alt: 'image5', class: 'tales'
    .item
      = image_tag 'image1.jpg', alt: 'image1', class: 'tales'
    .item
      = image_tag 'image3.jpg', alt: 'image3', class: 'tales'
    .item
      = image_tag 'image2.jpg', alt: 'image2', class: 'tales'
  a.left.carousel-control data-slide="prev" href="#myCarousel" 
    span.glyphicon.glyphicon-chevron-left
    span.sr-only Previous
  a.right.carousel-control data-slide="next" href="#myCarousel" 
    span.glyphicon.glyphicon-chevron-right
    span.sr-only Next
.container
  .row
    .col-md-12
      br
        center
          span.header2 = 'About Us'
        br
        br
      p style = "line-height:1.8em;"
        b = 'RBA Computer '
        'is a focused educational enterprise that firmly believes in empowering young minds with skills and enlightening them with knowledge to be the future leaders. Synonymous with INTEGRITY, INNOVATION and EXCELLENCE, RBA Computer was envisioned and founded by Avinash Sahoo in 2015
        and It is Directed By Deepika Kumari
      p style="line-height:1.8em;" 
        'Over the years, RBA Computer has evolved and grown exponentially into an initiative with a progressive outlook and a professional approach. It has consistently endeavoured to create entrepreneurs and leaders, to establish foundations of a knowledge based economy.'
      br
      p style = 'line-height:1.8em;" 
        'A vibrant and passionate team of RBA Computer has created a colossal pool of skilled resources with several path breaking ideas. This remains the mainstay of RBA Computer's achievements. The group further aspires to scale new altitudes of success.

app/views/pages/carrier.html.slim
#contentback
  = image_tag 'image1.jpg', alt: 'image1', class: 'tales'
br
.container
  .row
    .col-md-12
      br
      center
        span.mainheading = t('.carrier')
      br
      br
      .subhomeheading
        The RBA's strength is the quality and relationships of its staff, in addition to our great students and families. The District fosters a progressive philosophy with high standards for student achievement, conduct, and societal contribution.
        br
        br
        The RBA's members oversee functions of more than 1000 full-time and part-time  positions in the district.The RBA's team members are energetic and hard working, take pride in their work and are service-oriented.
        br
        br
        #dyk
          = image_tag 'dyk.jpg', alt: 'image1', class: 'tales'

app/views/pages/contact_us.html.slim
.space-20
  .container
    .row
      .col-md-5
        h4.contact-us
          = Address
        span style = "font-family:Open Sans;font-size:20px;"
          h5 style = "font-family:Open Sans;font-size:20px; color: #041525;"
            = 'Dilip Electronic Main Road Lachragardh'
        br
        h4.contact-us
          = 'Phones'
        h5 style = "color:#041525;"
          = '+91 - 7544802173 '
        br
          = ' +91 - 9430742215'
        br
        h4.contact-us
          = 'Email'
        h5 style = "color:#041525;"
          = 'rbacomputercenter@gmail.com'
        br

app/views/pages/offering_course.html.slim
.space-20
  .container
    .row
      .row.features
        .col-sm-12
          center
            span.header2
              = 'Excel Training from RBA Computers'
          br
          br
          p style = "line-height:1.8em;"
          | 
            Microsoft Excel is the most commonly used spreadsheet application.  Learning how to use Excel is an investment in both your personal and professional life. Excel makes it easy to monitor financial performance, such as business profit or loss, calculate payments on large purchases, plan a budget, or stay organized with checklists.
          br
          p style = 'line-height:1.8em;'
          |
            As an employee, learning how to use Excel efficiently provides value, since most jobs utilize this application. This opens up more opportunities for employment and career advancement.
          br
          p style = 'line-height:1.8em;'
          |
            When employees know how to use Excel, it improves their efficiency in the workplace. Employees who know how to create detailed worksheets, invoices, charts, and complex formulas achieve professional results in a fraction of the time.
          br
          p style = 'line-height:1.8em'
          |
            Excel training at RBA Computers includes basic to advanced courses. Whether you're brand new to Excel or seeking advanced knowledge, we've got it covered. Get Started Today!
      #accordion2.row.features
        .col-sm-12
          center
            span.header2
              = 'DCA'
          br
          br
          p style = 'line-height:1.8em;'
          |
            Diploma in Computer Applications acronym is DCA. The persons who are good at maths and interested in computer technology can go on to Diploma in Computer Application. This course gives the overlay of computer applications. There is demand for skilled person for handling Computer Applications.
          br
          p style = "line-height:1.8em;"
          |
            DCA is designed to build a strong foundation in programming, using object-oriented programming languages like Java and C#. It helps to develop skills in web page designing using HTML and JavaScript.
          br
          h3
            span = 'Course Duration : 6 months'    
      .row.features
        .col-sm-12
          center
            span.header2
              = 'ADCA'
          br
          br
          p style = "line-height:1.8em"
          |
            Advanced  Diploma in Computer Applications (ADCA) has been designed for  meeting the demand of the growing needs of experts in the fields of computers, internet, operating systems, office automation, programming languages, pagemaker, tally, hardware maintenance, web design, coreldraw etc.
          br
          h3
            span = 'Course Duration : 1 year'
      .row.features
        .col-sm-12
          center
            span.header2
              = 'TALLY'
          br
          br
          p style = "line-height:1.8em;"
            |
              Learn Tally from Tally Experts with vast knowledge in Practical Accounting. Our Training team includes Tally Experts and Chartered Accountant.
              For Both Beginners & for Advanced Learning.
              Beginners can join our Tally Classes at our place.
              Corporate training is also available for Corporate. To make your employee learn the new features in Tally and also solve their existing users.
          br
          h2
            span= 'Course Duration : 6 months'