config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'high_voltage/pages#show', id: 'about'

  namespace :admin do
    resources :members
    resources :courses
    resources :documents
    resources :certificates do 
      member do 
        get :download
      end
    end
  end

  authenticated :user do
    root 'admin/courses#index', as: :authenticated_root
  end

  resources :documents

end

app/models/address.rb
class Address < ApplicationRecord

  validates :first_name,
            :last_name,
            presence: true

  validates :mobile_number,
            numericality: true,
            allow_blank: true

  validates :email_id,
          uniqueness: true,
          format: { with: RubyRegex::Email }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certificate_general.rb
class CertificateGeneral < ApplicationRecord

  self.table_name = 'view_certificate_general'
  self.primary_key = 'id'

end

app/models/course.rb
class Course < ApplicationRecord

  validates :name, 
            :interval,
            presence: true

  validates :name,
            uniqueness: true

  has_many :course_members
  has_many :members, through: :course_members

  accepts_nested_attributes_for :members

end

app/models/course_member.rb
class CourseMember < ApplicationRecord
  belongs_to :member
  belongs_to :course
end

app/models/document.rb
class Document < ApplicationRecord

  has_attached_file :document_list,
           styles: { medium: "300x300>", thumb: "100x100>"},
           s3_protocol: 'https'

  validates :document_list,
             presence: true

  validates_attachment_content_type :document_list, :content_type => ['image/jpeg', 'image/png']
  validates :document_list, attachment_presence: true

end

app/models/member.rb
class Member < ApplicationRecord

  has_one :address, as: :resource, dependent: :destroy
  has_many :course_members
  has_many :courses, through: :course_members

  delegate :first_name, to: :address, allow_nil: true
  delegate :middle_name, to: :address, allow_nil: true
  delegate :last_name, to: :address, allow_nil: true
  delegate :email_id, to: :address, allow_nil: true
  delegate  :interval, to: :courses
  delegate  :mobile_number, to: :address, allow_nil: true

  accepts_nested_attributes_for :address

  attr_reader :course

  scope :certificate_not_generated, -> { where( certificategenerated: false ) }

  def name
    full_name = ''
    full_name << first_name.to_s << middle_name.to_s << last_name.to_s
    full_name
  end

  def generate_certificate!
    if course_completed?
      self.update_attribute(:certificategenerated, true)
    end
  end

  def course_completed?
    (((Time.now - self.created_at)/1.day).round).to_i >=  self.course_duration*30
  end 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/certificates_controller.rb
class Admin::CertificatesController < AdminController

  def index
    @cerificates =  CertificateGeneral.all
  end

  def download
    @certificate = CertificateGeneral.find(params[:id])
    respond_to  do |format|
      format.pdf do
        render pdf: "#{@certificate.id}-#{@certificate.member_name}-certificate",
        template: 'admin/certificates/download.html.slim'
      end
    end
  end

end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < AdminController

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      respond_to do |format|
        format.js
      end
    else
      render 'new'
    end
  end

  private

  def course_params
    params.require(:course).permit(
      :name,
      :interval
    )
  end

end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < AdminController

  include GallaryController

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to admin_documents_path
    else
      render 'new'
    end
  end

  private

  def document_params
    params.require(:document).permit(
      :document_list
    )
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < AdminController

  before_action :find_course

  def index
    @members = @course.try(:members)
  end

  def new
    @member = @course.members.build
    @member.course_duration = @course.interval
    @address = @member.build_address
  end

  def create
    @member = @course.members.new(member_params)
    if @course.save && @member.save
      respond_to do |format|
        flash[:notice] = 'Member is created successfully'
        format.js
      end
    else
      render 'new'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    if @member.destroy
        flash[:notice] = 'Member is destroyed successfully'
        redirect_to admin_members_path(course: params[:course])
    else
      render 'new'
    end
  end


  private

  def find_course
    @course = Course.find_by_name(params[:course])
  end

  def member_params
    params.require(:member).permit(
      :fees,
      :course_duration,
      address_attributes:
      [
        :first_name,
        :middle_name,
        :last_name,
        :email_id,
        :mobile_number
      ]
    )
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_filter :valid_request

  protected

  def after_sign_in_path_for(resource)
    admin_courses_path
  end

  def valid_request
    if restricted_action
      redirect_to new_user_session_path
    end
  end

  def restricted_action
    controller_name == 'registrations' && action_name == 'new'
  end

end

app/controllers/concerns/gallary_controller.rb
module GallaryController
  extend ActiveSupport::Concern
  included do
    def index
      @documents = Document.all
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include GallaryController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def members_tabs(course)
    Course.all.map(&:name).each do |course_name|
      course.item course_name, course_name, admin_members_path(course: course_name),
        highlights_on: lambda { params[:course] == course_name }
    end
  end

  def custom_navigation
    'navbar-navbar-default.custom-nav' 
  end

  def is_pdf_request?
    params[:format] == 'pdf'
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/admin/certificates/download.html.slim
- if is_pdf_request?
  = wicked_pdf_stylesheet_link_tag 'application'
.container.bordered
  .space-40
    .row
      .col-md-12
        br
          center
            span
              = image_tag wicked_pdf_asset_base64('certificate_logo.png')
          br
          br
          center
            h3 style = "line height:1.8em;"
              | This is To Certify That
            br
            h3 style = "line height:1.8em;" = "#{@certificate.member_name}"
          br
          h4 style = "line height:1.8em;"
            | 
              has completed the course #{@certificate.course_name} of #{@certificate.course_duration} months
              and hereby awarded this certificate
          br
          br
            .pull-right
              label.control-label = "Date: #{Date.today}"

app/views/admin/certificates/index.html.slim
.space-20
  h4.text-center = t('.certificates')
.container
  .space-20
    .col-md-12
      .table-wrapper
        .table-responsive
          table.table.table-bordered.table-striped#bootstrap-table
            thead
              tr
                th data-sortable='true' = t('.reference_id')
                th data-sortable='true' = t('.member_name')
                th data-sortable='true' = t('.course_name')
                th data-sortable='true' = t('.course_duration')
                th  = t('.action')
            tbody
              - @cerificates.each do |certificate|
                  tr
                    td = certificate.id
                    td = certificate.member_name
                    td = certificate.course_name
                    td = certificate.course_duration
                    td = link_to t('.download Certificate'), download_admin_certificate_path(certificate, format: :pdf), class: 'btn btn-success'

app/views/admin/courses/_course_row.html.slim
tr
  td = course.id
  td = course.name
  td = course.created_at
  td = course.updated_at

app/views/admin/courses/_form.html.slim
.course.modal
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type='button' &times
        h4.text-center = t('.add_new_course')
      = form_for [:admin, @course], remote: true,  html: {class: 'form-horizontal'} do |f|
        .modal-body
          .form-group
            label.control-label.col-sm-4 = t('.name')
            .col-sm-8
              = f.text_field :name, class: 'form-control'
          .form-group
            label.col-sm-4.control-label= t('.duration_of_course')
            .col-sm-8
              = f.text_field :interval, class: 'form-control'
        .form-group.space-20
          .modal-footer
            .col-sm-12.pull-right
              = f.submit 'save', data: { confirm: 'Are You Sure want to add New Course'}, 
                class: 'btn btn-success'

app/views/admin/courses/create.js.erb
<% if @course.errors.blank? %>
  $('.course').modal('hide');
  $('table tbody').append('<%= j render "course_row", course: @course %>');
<% else %>
  
<% end %>

app/views/admin/courses/index.html.slim
.space-20
h4.text-center = t('.courses')
.container
  .row
    = link_to t('.add_new_course'), new_admin_course_path, remote: true, class: ' btn btn-success pull-right'
  .space-20
    .col-md-12
      .table-wrapper
        .table-responsive
          table.table.table-bordered.table-striped#bootstrap-table
            thead
              tr
                th data-sortable='true' = t('general.reference_id')
                th data-sortable='true' = t('.name')
                th data-sortable= 'true' = t('.duration_of_course')
                th data-sortable='true' = t('general.updated_at')
                th data-sortable='true' = t('general.created_at')
            tbody
              - @courses.each do |course|
                tr
                  td = course.id
                  td = course.name
                  td = course.interval
                  td = course.created_at
                  td = course.updated_at

app/views/admin/courses/new.js.erb
$('.course').modal('hide');
$('<%= j render "form" %>').modal();

app/views/admin/documents/index.html.slim
.container
  .row
    = link_to 'Add New Images', new_admin_document_path, class: 'btn btn-success pull-right'
  - @documents.each do |document|
    .col-xs-8.col-md-4
      .panel
        .panel-body
          = image_tag document.document_list.url(:medium), class: 'image-size'

app/views/admin/documents/new.html.slim
= form_for [:admin, @document], html: { class: 'form-horizontal' } do |f|
  .form-group
    label.col-sm-2 = t('.upload_files')
    .col-sm-9
      = f.file_field :document_list
  .form-group
    .col-sm-12
      = f.submit I18n.t('general.submit'), class: 'btn btn-success submit-img'
      |&nbsp;
      = link_to 'Back', admin_documents_path, rel: "modal:close", class: 'btn btn-danger'
javascript:
  if ($('#document_document_list').val() == ''){
    $('.submit-img').hide()
  }
  $('#document_document_list').change(function(){
    $('.submit-img').show()
  });

app/views/admin/members/_form.html.slim
.member.modal
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type='button' &times
        h4.text-center = t('.add_new_student')
      = form_for [:admin, @member], remote: true, html: { class: 'form-horizontal' } do |f|
        = hidden_field_tag :course, params[:course]
        = f.fields_for :address, @address do |address| 
          .modal-body
            .form-group
              label.control-label.col-sm-4 = t('.first_name')
              .col-sm-8
                = address.text_field :first_name, class: 'form-control'
            .form-group
              label.control-label.col-sm-4 = t('.middle_name')
              .col-sm-8
                = address.text_field :middle_name, class: 'form-control'
            .form-group
              label.control-label.col-sm-4 = t('.last_name')
              .col-sm-8
                = address.text_field :last_name, class: 'form-control'
            .form-group
              label.control-label.col-sm-4 = t('.email')
              .col-sm-8
                = address.text_field :email_id, class: 'form-control'
            .form-group
              label.control-label.col-sm-4 = t('.mobile_number')
              .col-sm-8
                = address.text_field :mobile_number, class: 'form-control'
            .form-group
              label.control-label.col-sm-4 = t('.fees')
              .col-sm-8
                = f.text_field :fees, class: 'form-control'
                = f.hidden_field :course_duration
        .form-group
          .modal-footer
            .col-sm-12.pull-right
              = f.submit 'save', data: {confirm: 'are you sure want to add new student'}, 
                class: 'btn btn-success'

app/views/admin/members/_member_row.html.slim
tr
  td = member.id
  td = member.name
  td = member.email_id
  td = member.address.try(:address)
  td = member.fees
  td = member.mobile_number
  td = member.updated_at
  td = link_to 'delete', admin_member_path(member, course: params[:course]), method: :delete, class: 'btn btn-danger'

app/views/admin/members/create.js.erb
<% if @member.errors.blank? %>
  $('.member').modal('hide');
  $('table tbody').append('<%= j render "member_row", member: @member %>');
<% else %>
<% end %>

app/views/admin/members/index.html.slim
.member-index
  h4.text-center = "Member Of #{params[:course]}"
  .container
    .row
      = link_to t('.add_new_student'), new_admin_member_path(course: params[:course]), remote: true, class: 'btn btn-success pull-right'
    .col-md-12
      .table-wrapper
        .table-responsive
          table.table.table-bordered.table-striped#bootstrap-table
            thead
              tr
                th data-sortable='true' = t('general.reference_id')
                th data-sortable='true' = t('.name')
                th data-sortable='true' = t('.email')
                th data-sortable='true' = t('.address')
                th data-sortable='true' = t('.fees')
                th data-sortable='true' = t('.mobile_number')
                th data-sortable= 'true' = t('general.updated_at')
                th = t('general.delete')
            tbody
              - @members.each do |member|
                tr
                  td = member.id
                  td = member.name
                  td = member.email_id
                  td = member.address.try(:address)
                  td = member.fees
                  td = member.mobile_number
                  td = member.updated_at
                  td = link_to 'Delete', admin_member_path(member, course: params[:course]), method: :delete, data: {confirm: 'are you sure want to delete student'}, class: 'btn btn-danger'

app/views/admin/members/new.js.erb
$('.member').modal('hide');
$('<%= j render "form" %>').modal();

app/views/documents/index.html.slim
.space-20
  .container
    - @documents.each do |document|
      .col-xs-8.col-md-4
        .panel
          .panel-body
            = image_tag document.document_list.url, class: 'image-size'